inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - config/**/*
    - db/**/*
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true
Metrics/LineLength:
  Max: 99
Documentation:
  Enabled: false

# Do not check for FrozenStringLiterals until ruby 3.0
Style/FrozenStringLiteralComment:
  Enabled: false
